In [2]:
import numpy as np
import h5py
import tensorflow as tf
import hls4ml

from qkeras import *
from qkeras.utils import load_qmodel

/afs/cern.ch/work/a/adpol/l1calotriggerad/synthesis/hls4ml/converters/__init__.py:15: UserWarning: WARNING: Pytorch converter is not enabled!
  warnings.warn("WARNING: Pytorch converter is not enabled!")


In [9]:
model = load_qmodel('./ML_CMSL1CaloTrigger/saved_models/qmodel_oct24');
model.summary()

2023-02-01 10:00:06.488557: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-01 10:00:06.489451: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-01 10:00:06.527583: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-01 10:00:06.528063: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-01 10:00:06.528497: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from S


Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 2} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 2} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 9} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 9} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 2, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 15} and quantized_bits(16,2,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 2, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 15} and quantized_bits(16,2,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 2} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 2} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 9} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 4, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 9} and quantized_bits(16,4,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 2, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 15} and quantized_bits(16,2,1,alpha='auto')).



Two checkpoint references resolved to different objects ({'class_name': 'quantized_bits', 'config': DictWrapper({'bits': 16, 'integer': 2, 'symmetric': True, 'alpha': 'auto', 'keep_negative': True, 'use_stochastic_rounding': False, 'qnoise_factor': 1.0}), 'shared_object_id': 15} and quantized_bits(16,2,1,alpha='auto')).


In [617]:
hls4ml.model.optimizer.get_optimizer(
    'output_rounding_saturation_mode'
).configure(
    layers=['relu1', 'relu2'],
    rounding_mode='AP_RND',
    saturation_mode='AP_SAT',
    saturation_bits='AP_SAT'
)
hls4ml.model.optimizer.get_optimizer(
    'eliminate_linear_activation'
)

hls_config = hls4ml.utils.config_from_keras_model(model, granularity='name')

hls_config['Model']['ReuseFactor'] = 4
hls_config['Model']['Strategy'] = 'Resource'
hls_config['Model']['ClockPeriod']  = 6.25
hls_config['Model']['Precision'] = 'ap_fixed<16, 6>'
# hls_config['Model']['Trace']  = True

for layer in hls_config['LayerName'].keys():
    hls_config['LayerName'][Layer]['Strategy'] = 'Resource'
    hls_config['LayerName'][Layer]['ReuseFactor'] = 4
    # hls_config['LayerName'][Layer]['Trace'] = True
    
    if Layer == 'In':
        hls_config['LayerName'][layer]['Precision']['accum'] = 'ap_ufixed<10, 10>'
        hls_config['LayerName'][layer]['Precision']['result'] = 'ap_ufixed<10, 10>'

    if Layer == 'conv':
        hls_config['LayerName'][layer]['Precision']['accum'] = 'ap_fixed<20, 17>'
        hls_config['LayerName'][layer]['Precision']['result'] = 'ap_fixed<20, 17>'
        hls_config['LayerName'][layer]['Strategy'] = 'Resource'
        hls_config['LayerName'][layer]['ReuseFactor'] = 1
        hls_config['LayerName'][layer]['ParallelizationFactor'] = 8

    if Layer == 'conv_linear':
        hls_config['LayerName'][layer]['Precision'] = 'ap_fixed<17, 8>'

    if Layer == 'dense1':
        hls_config['LayerName'][layer]['Precision']['accum'] = 'ap_fixed<19, 12>'
        hls_config['LayerName'][layer]['Precision']['result'] = 'ap_fixed<19, 12>'

    if Layer == 'dense1_linear':
        hls_config['LayerName'][layer]['Precision'] = 'ap_fixed<17, 8>'

    if Layer == 'output':
        hls_config['LayerName'][layer]['Precision']['accum'] = 'ap_fixed<17, 9>'
        hls_config['LayerName'][layer]['Precision']['result'] = 'ap_fixed<17, 9>'

    if Layer == 'output_linear':
        hls_config['LayerName'][layer]['Precision'] = 'ap_ufixed<13, 7>'

hls_config['LayerName']['conv_alpha'] = {}
hls_config['LayerName']['conv_alpha']['Precision'] = {}
hls_config['LayerName']['conv_alpha']['Precision']['scale'] = 'ap_fixed<17, 0>'
hls_config['LayerName']['conv_alpha']['Precision']['result'] = 'ap_fixed<17, 8>'
hls_config['LayerName']['conv_alpha']['Precision']['accum'] = 'ap_fixed<17, 8>'
hls_config['LayerName']['conv_alpha']['Precision']['bias'] = 'ap_int<1>'

hls_config['LayerName']['dense1_alpha'] = {}
hls_config['LayerName']['dense1_alpha']['Precision'] = {}
hls_config['LayerName']['dense1_alpha']['Precision']['scale'] = 'ap_fixed<14, 0>'
hls_config['LayerName']['dense1_alpha']['Precision']['result'] = 'ap_fixed<17, 8>'
hls_config['LayerName']['dense1_alpha']['Precision']['accum'] = 'ap_fixed<17, 8>'
hls_config['LayerName']['dense1_alpha']['Precision']['bias'] = 'ap_int<1>'

hls_config['LayerName']['output_alpha'] = {}
hls_config['LayerName']['output_alpha']['Precision'] = {}
hls_config['LayerName']['output_alpha']['Precision']['scale'] = 'ap_fixed<8, 0>'
hls_config['LayerName']['output_alpha']['Precision']['result'] = 'ap_ufixed<13, 7>'
hls_config['LayerName']['output_alpha']['Precision']['accum'] = 'ap_fixed<14, 7>'
hls_config['LayerName']['output_alpha']['Precision']['bias'] = 'ap_int<1>'

cfg = hls4ml.converters.create_config(part="xc7vx690tffg1927-2")
cfg['IOType'] = 'io_parallel'
cfg['HLSConfig'] = hls_config
cfg['KerasModel'] = model
cfg['ClockPeriod']  = 6.25
cfg['OutputDir']  = 'cicada/'
cfg['Part'] = 'xc7vx690tffg1927-2'

Interpreting Model
Topology:
Layer name: In, layer type: Input
Layer name: conv, layer type: QConv2D
  -> Activation (linear), layer name: conv
Layer name: relu1, layer type: QActivation
  -> Activation (quantized_relu(16,4)), layer name: relu1
Layer name: dense1, layer type: QDense
  -> Activation (linear), layer name: dense1
Layer name: relu2, layer type: QActivation
  -> Activation (quantized_relu(16,4)), layer name: relu2
Layer name: output, layer type: QDense
  -> Activation (linear), layer name: output


In [618]:
hls_model = hls4ml.converters.keras_to_hls(cfg)
hls4ml.model.optimizer.get_optimizer(
    'output_rounding_saturation_mode'
).configure(layers=[])
hls_model.compile()

Interpreting Model
Topology:
Layer name: In, layer type: InputLayer, input shapes: [[None, 252]], output shape: [None, 252]
Layer name: reshape, layer type: Reshape, input shapes: [[None, 252]], output shape: [None, 18, 14, 1]
Layer name: conv, layer type: QConv2D, input shapes: [[None, 18, 14, 1]], output shape: [None, 8, 6, 3]
Layer name: relu1, layer type: Activation, input shapes: [[None, 8, 6, 3]], output shape: [None, 8, 6, 3]
Layer name: flatten, layer type: Reshape, input shapes: [[None, 8, 6, 3]], output shape: [None, 144]
Layer name: dense1, layer type: QDense, input shapes: [[None, 144]], output shape: [None, 20]
Layer name: relu2, layer type: Activation, input shapes: [[None, 20]], output shape: [None, 20]
Layer name: output, layer type: QDense, input shapes: [[None, 20]], output shape: [None, 1]
Creating HLS model
quant None
quant None
quant None
Writing HLS project
Done


In [590]:
# hls4ml.utils.plot_model(hls_model, show_shapes=False, show_precision=True, to_file=None)

In [591]:
# hls4ml.model.profiling.numerical(model=model, hls_model=hls_model)

# Test vectors: check the output

In [45]:
# Test vector, zeros:
test_vector_b = np.zeros((1, 252)) + 0.

# Test vector, mean zero bias, 2018 run D:
test_vector_c = np.array([[2, 1, 1, 2, 1, 2, 3, 3, 3, 2, 3, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 2, 3, 1, 1, 2],
       [2, 1, 1, 1, 2, 2, 3, 3, 2, 2, 3, 1, 1, 2],
       [2, 1, 1, 2, 1, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 4, 3, 2, 4, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 2, 2, 1, 1, 2],
       [2, 1, 1, 3, 2, 3, 5, 2, 2, 1, 3, 1, 1, 2],
       [2, 1, 1, 2, 2, 3, 4, 3, 2, 2, 2, 1, 1, 3],
       [2, 1, 1, 2, 2, 3, 4, 3, 2, 1, 2, 1, 1, 3],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 3, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [0, 0, 0, 2, 2, 2, 3, 3, 2, 2, 2, 1, 1, 2],
       [0, 0, 0, 3, 2, 3, 5, 4, 3, 2, 4, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 4, 3, 2, 2, 4, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 3, 1, 1, 2]]).reshape(1, 252) + 0.

# Test vector, signal haa4b_ma15_powheg:
test_vector_d = np.array([[8, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 8],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 9],
       [9, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 9],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 9],
       [8, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 8],
       [8, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 8],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 9],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 9],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 8],
       [8, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 8],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 8],
       [9, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 9],
       [9, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 2, 2, 9],
       [8, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 8],
       [8, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 8],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 9],
       [9, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 9],
       [8, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 2, 2, 8]]).reshape(1, 252) + 0.

# Test vector, mean zero bias, 2018 run D:
test_vector_e = np.array([[2, 1, 1, 2, 1, 2, 3, 3, 3, 2, 3, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 2, 3, 1, 1, 2],
       [2, 1, 1, 1, 2, 2, 1023, 3, 2, 2, 3, 1, 1, 2],
       [2, 1, 1, 2, 1, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 1023, 1023, 2, 3, 4, 3, 2, 4, 1023, 1, 2],
       [2, 1, 1023, 1023, 2, 2, 3, 3, 2, 2, 2, 1, 1, 2],
       [2, 1, 1, 3, 2, 3, 5, 2, 2, 1, 3, 1023, 1, 2],
       [2, 1, 1, 2, 2, 3, 4, 3, 2, 2, 2, 1, 1, 3],
       [2, 1, 1, 2, 2, 3, 4, 3, 2, 1, 2, 1, 1, 3],
       [2, 1, 1, 2, 2, 2, 3, 3, 1023, 1, 2, 1, 1, 2],
       [2, 1, 1, 1023, 2, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 3, 3, 2, 1, 3, 1, 1, 2],
       [2, 1, 1, 2, 1023, 2, 3, 3, 2, 1, 2, 1, 1, 2],
       [0, 1023, 0, 2, 2, 2, 3, 3, 2, 2, 2, 1, 1, 2],
       [0, 0, 0, 3, 2, 3, 5, 4, 3, 2, 4, 1, 1, 2],
       [2, 1, 1, 2, 2, 2, 4, 3, 2, 2, 1023, 1, 1, 2],
       [2, 1023, 1, 2, 2, 2, 3, 3, 2, 1, 3, 1, 1, 2]]).reshape(1, 252) + 0.

In [619]:
abs(model.predict(test_vector_b) - hls_model.predict(test_vector_b)) < 0.5

array([[ True]])

In [620]:
abs(model.predict(test_vector_b+1) - hls_model.predict(test_vector_b+1))  < 0.5

array([[ True]])

In [621]:
abs(model.predict(test_vector_c) - hls_model.predict(test_vector_c)) < 0.5

array([[ True]])

In [622]:
abs(model.predict(test_vector_d) - hls_model.predict(test_vector_d)) < 0.5

array([[ True]])

In [623]:
datasets = ['/eos/user/a/adpol/L1AD/Signal/120X/haa4taus_ma15_powheg.h5',
            '/eos/user/a/adpol/L1AD/Signal/120X/haa4b_ma50_powheg.h5',
            '/eos/user/a/adpol/L1AD/Signal/120X/emj-mMed-800-mDark-10-ctau-1000.h5']

for dataset in datasets:
    X_test = h5py.File(dataset,'r')['CaloRegions']
    max_diff = 0
    m_idx = -1
    for idx in range(4000):
        vector = X_test[idx].reshape(1, 252) + 0.
        diff = abs(float(model.predict(vector) - hls_model.predict(vector)))
        if max_diff < diff:
            max_diff = diff
            m_idx = i
        if diff > 0.5:
            print('Error', diff)
            print()
            print(dataset)
            print(i)
            break
m_diff, m_i

(0.4959068298339844, 2814)

# Debug

In [267]:
model.predict(x[12].reshape(1, 252) + 0.), hls_model.predict(x[12].reshape(1, 252) + 0.)

(array([[41.371735]], dtype=float32), array([41.25]))

In [261]:
tv = x[12].reshape(1, 252) + 0.

hls4ml_pred, hls4ml_trace = hls_model.trace(tv)
keras_trace = hls4ml.model.profiling.get_ymodel_keras(model, tv)

Recompiling myproject with tracing
Writing HLS project
Done
Processing In in Keras model...
Processing reshape in Keras model...
Processing conv in Keras model...
Processing relu1 in Keras model...
Processing flatten in Keras model...
Processing dense1 in Keras model...
Processing relu2 in Keras model...
Processing output in Keras model...
Done taking outputs for Keras model.


In [262]:
hls4ml_pred

array([-40.234375])

In [263]:
keras_trace

{'reshape': array([[[[  0.],
          [  0.],
          [ 15.],
          [  1.],
          [  0.],
          [110.],
          [  2.],
          [  8.],
          [  1.],
          [  2.],
          [  0.],
          [  0.],
          [  2.],
          [ 16.]],
 
         [[  0.],
          [  1.],
          [  0.],
          [  0.],
          [  0.],
          [  1.],
          [  1.],
          [  4.],
          [  4.],
          [  0.],
          [  0.],
          [  0.],
          [  4.],
          [  2.]],
 
         [[  2.],
          [  2.],
          [  2.],
          [  2.],
          [  1.],
          [  0.],
          [115.],
          [ 13.],
          [ 24.],
          [ 74.],
          [  1.],
          [  3.],
          [  0.],
          [  2.]],
 
         [[  0.],
          [  0.],
          [  0.],
          [  1.],
          [  9.],
          [  6.],
          [ 16.],
          [ 10.],
          [  0.],
          [  2.],
          [  1.],
          [  1.],
        

In [264]:
hls4ml_trace

{'conv': array([[[[ 1.4175000e+02, -1.1250000e+02, -8.3875000e+01],
          [ 1.9200000e+02, -2.1137500e+02,  2.9200000e+02],
          [ 2.6303750e+03, -7.1125000e+01,  1.2727500e+03],
          [ 1.5577500e+03,  6.2662500e+02,  1.8608750e+03],
          [ 7.4225000e+02, -3.5012500e+02,  8.5175000e+02],
          [ 7.0625000e+01, -7.5375000e+01, -2.9625000e+01]],
 
         [[ 8.1375000e+01, -5.1125000e+01,  4.5250000e+01],
          [ 1.6500000e+02, -8.6750000e+01, -4.6375000e+01],
          [ 1.0397500e+03, -8.7612500e+02, -9.9612500e+02],
          [ 1.8481250e+03, -1.3123750e+03,  1.9030000e+03],
          [ 1.4602500e+03,  3.6900000e+02,  1.0017500e+03],
          [ 9.9375000e+01,  2.3625000e+01,  4.8375000e+01]],
 
         [[ 1.2525000e+02,  2.2500000e+01,  7.9000000e+01],
          [ 1.6375000e+02, -1.2600000e+02,  1.1312500e+02],
          [ 2.1312500e+02,  5.9625000e+01,  1.7962500e+02],
          [ 4.1112500e+02, -4.3337500e+02,  1.3212500e+02],
          [ 4.6141250e+03,

# Synthesis: command line or here

In [12]:
# Change the uncertainty in tcl: set_clock_uncertainty 30% {get_clocks default}

#!grep -n create_clock VersionD/build_prj.tcl | awk -F ":" '{print$1}' | ( read line; echo "$((line + 1)) ") | xargs -I {} sed -i '{} i set_clock_uncertainty 30% {get_clocks default}' VersionD/build_prj.tcl 

In [13]:
# Run Vivado HLS

# !vivado_hls -f CaloADTrigger/build_prj.tcl "reset=1 synth=1 csim=0 cosim=0 validation=0 export=0 vsynth=0"

In [14]:
# Get the report

# !cat CaloADTrigger-synth2/myproject_prj/solution1/syn/report/myproject_csynth.rpt